apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp-h2
  name: webapp-h2
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp-h2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%    
  template:
    metadata:
      labels:
        app: webapp-h2
    spec:
      containers:
        - image: irffan/webapp-h2:v1
          name: webapp-h2

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-h2
spec:
  type: NodePort
  selector:
    app: webapp-h2
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001